name: Thanh Nguyen
markdown: kramdown
permalink: /blog/:year/:month/:day/:title
# paginate_path: /blog/page/:num/
sass:
  style: compressed
username: "@Thanh Nguyen"
avatar: "https://avatars0.githubusercontent.com/u/26478347?v=3&u=5b57c96c0ad797a179dd6265e095ea49e8c49480&s=400"
allpost: "https://thanhnguyenq.github.io/allpost.json"

# gems:
#   - jekyll-paginate
tagURL : "/pages/blog/tag/?tag="
renameURL : "https://thanhnguyenq.github.io/pages/drive/rename/?ref="
